markdown: rdiscount
pygments: true
permalink: pretty
url: http://www.zhuyinghao.com
title: Truman's door 
description: Personal website of tony.
author: tony 
email: loxeyer@gmail.com
github: loxeyer
twitter: loxeyer
facebook: zhuyinghao
atom: http://feeds.feedburner.com/~u/10468393075769300256

paginate: 5

exclude:
  - Rakefile
  - README.markdown

