markdown: rdiscount
pygments: true
permalink: pretty
url: http://www.zhuyinghao.com
title: 楚国之门 
description: Personal website of tony.
author: tony 
email: loxeyer@gmail.com
github: loxeyer
twitter: loxeyer
facebook: zhuyinghao
atom: http://feeds.feedburner.com/loxeyer

paginate: 5

exclude:
  - Rakefile
  - README.markdown

